version: 2.1

workflows:
  version: 2
  branch:
    jobs:
      - check:
          context: [aws]
      - test:
          context: [aws]
      - makepress-orb/release-please-single:
          context: [lulubot]
          filters:
            branches:
              only: main
  release:
    jobs:
      - build-and-publish-tagged:
          context: [aws, crates.io]
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
jobs:
  check:
    executor: makepress-orb/rust
    steps:
      - checkout
      - makepress-orb/with-rust:
          steps:
            - run: just check
  test:
    executor: makepress-orb/rust
    steps:
      - checkout
      - makepress-orb/with-rust:
          steps:
            - run: just test
  build-and-publish-tagged:
    executor: makepress-orb/rust
    steps:
      - checkout
      - makepress-orb/with-rust:
          steps:
            - run: cargo login
            - run: cargo publish
orbs:
  makepress-orb: makepress/makepress-orb@2.3.0